### PR TITLE
Added 5 more places

### PR DESCRIPTION
**Pull request by pbisen**
added nagpur, pilani, melbourne, loharu, canberra

### CODE REVIEW

**Review by Gautam-Arora24 — COMMENTED** [review]
Kindly remove all the places of India as there already have been too many places of India. Add some new places and also make sure you star the repo. Then you are good to go :)

**Comment by pbisen** [comment]
Please review this updated version of data.json

**Comment by Gautam-Arora24** [comment]
Kindly resolve conflicts @pbisen Then you are good to go

**Comment by pbisen** [comment]
Please review the resolved version.

**Pull request merged**
