### PR TITLE
added more cities

### PR DESCRIPTION
**Pull request by jakubkoje**

### CODE REVIEW

**Review by Gautam-Arora24 — COMMENTED** [review]
Kindly add some more pairs @jakubkoje

**Comment by jakubkoje** [comment]
@Gautam-Arora24 I added some more pairs.

**Review by Gautam-Arora24 — APPROVED** [review]

**Comment by Gautam-Arora24** [comment]
Thank you for your commits. Make sure you star the repo :)

**Comment by jakubkoje** [comment]
@Gautam-Arora24 Could you please label this PR as 'hacktoberfest-accepted'? I would greatly appreciate it.

**Comment by Gautam-Arora24** [comment]
Done. Kindly check it

**Pull request merged**
